#!/bin/sh

tmpfile="$(mktemp)"

echo "$2" | grep -qE '^[0-9]+$' && height="$2" || height="$(($(stty size | awk '{print $1}') - 5))"
[ "$DEBUG" = "true" ] && echo "Using height $height"

url="https://t.nhentai.net/galleries/$1/cover.png"
curl -fsSLo "$tmpfile.jpg" "$url"

if [ "$TERM" = "xterm-kitty" ]; then
    command -v convert > /dev/null 2>&1 && neofetch --kitty "$tmpfile.jpg" || kitty_imagemagick_warn=true
    if [ "$kitty_imagemagick_warn" = "true" ]; then
        jp2a --height="$height" "$tmpfile.jpg" > "$tmpfile"
        neofetch --source "$tmpfile"
    fi
else
    jp2a --height="$height" "$tmpfile.jpg" > "$tmpfile"
    neofetch --source "$tmpfile"
fi

rm "$tmpfile" "$tmpfile.jpg"

[ "$kitty_imagemagick_warn" = "true" ] && echo "WARN: imagemagick is required for kitty image backend"
