#!/bin/bash

image_file="$(mktemp)"
chafa_output="$(mktemp)"
system_info="$(mktemp)"

random=$(curl -sl "https://wholesomelist.com/random")
id=$(echo "$random" | grep -oP '(?<=list\/)\S+')

nurl=$(curl -fsSL "https://wholesomelist.com/list/$id" 2>/dev/null | grep -m1 -o "https://nhentai\.net/g/[[:digit:]]*")
tag=$(echo "$nurl" | grep -o "[[:digit:]]*")

url="https://wholesomelist.com/asset/$id.jpg"

if curl -fsSLo "$image_file" "$url"; then

  if [ "$1" = "--pixel" ]; then
    chafa "$image_file" --center=off -s 23x34 > "$chafa_output"
    neofetch --off --gap 0 > "$system_info"
    paste -d '' "$chafa_output" "$system_info"
  else
    neofetch "$1" $image_file
  fi

  if [ "$tag" = "" ]; then
    printf "No matching NHentai tag found"
  else
    printf "NHentai tag: #%s\n" "$tag"
  fi

else
  echo "Failed to download the image."
fi

rm "$image_file" "$chafa_output" "$system_info"
